version: '3.4'

services:
  coopgateway:
    image: ${DOCKER_REGISTRY-}coopgateway
    container_name: microthings_gateway
    build:
        context: .
        dockerfile: gateway.dockerfile
    ports:
        - "5000:80"
    networks:
        - microthings_bridge

  loggingservice:
    image: loggingservice
    container_name: loggingservice
    restart: always
    environment: 
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://+:80
        ApplicationSettings:DatabaseType: MySql
    build:
        context: .
        dockerfile: loggingservice.dockerfile
    ports:
        - "80"
    networks:
        - microthings_bridge
        
  notificationsservice:
    image: notificationsservice
    container_name: notificationsservice
    restart: always
    environment: 
        ASPNETCORE_URLS: http://+:80
    build:
        context: .
        dockerfile: notificationsservice.dockerfile
    ports:
        - "80"
    networks:
        - microthings_bridge

  microthings_rabbitmq:
    image: rabbitmq:3.9-management
    container_name: 'microthings_rabbitmq'
    ports:
        - 5672:5672 #AMQP port
        - 15672:15672 #management UI port
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    networks:
        - microthings_bridge

networks:
    microthings_bridge:
        name: microthings_bridge
        driver: bridge
