version: '3.4'

services:
  coopgateway:
    image: ${DOCKER_REGISTRY-}coopgateway
    container_name: microthings_gateway
    build:
        context: .
        dockerfile: gateway.dockerfile
    ports:
        - "5000:80"
    networks:
        - microthings_bridge

  loggingservice:
    image: loggingservice
    container_name: loggingservice
    restart: always
    environment: 
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://+:5001
        ApplicationSettings:DatabaseType: MySql
    build:
        context: .
        dockerfile: loggingservice.dockerfile
    ports:
        - "80"
    networks:
        - microthings_bridge

networks:
    microthings_bridge:
        name: microthings_bridge
        driver: bridge
